# 4장. 텐서플로 데이터셋으로 공개 데이터 사용하기

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://nbviewer.jupyter.org/github/rickiepark/aiml4coders/blob/main/ch04/04-tfds.ipynb"><img src="https://jupyter.org/assets/share.png" width="61" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/aiml4coders/blob/main/ch04/04-tfds.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

## TFDS 시작하기

In [7]:
import tensorflow as tf
import tensorflow_datasets as tfds

mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
    print(item)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/fashion_mnist/3.0.1.incompleteZPBRXW/fashion_mnist-train.tfrecord*...:   0%|  …

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/fashion_mnist/3.0.1.incompleteZPBRXW/fashion_mnist-test.tfrecord*...:   0%|   …

Dataset fashion_mnist downloaded and prepared to ~/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.
train
test


In [8]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>


In [9]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


In [10]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


In [11]:
mnist_test, info = tfds.load(name="fashion_mnist", with_info="true")
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_path='~/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author  

## 케라스 모델에서 TFDS 사용하기

In [12]:
mnist = tf.keras.datasets.fashion_mnist

(training_images, training_labels), (test_images, test_labels) = \
    mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


In [13]:
(training_images, training_labels), (test_images, test_labels) = \
    tfds.as_numpy(tfds.load('fashion_mnist',
                            split = ['train', 'test'], 
                            batch_size=-1, 
                            as_supervised=True))

In [14]:
(training_images, training_labels), (test_images, test_labels) = \
    tfds.load('fashion_mnist', 
              split = ['train', 'test'],
              batch_size=-1, 
              as_supervised=True)

training_images = tf.cast(training_images, tf.float32) / 255.0
test_images = tf.cast(test_images, tf.float32) / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28,1)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 2ms/step - loss: 0.5318 - accuracy: 0.8121
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4015 - accuracy: 0.8559
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3671 - accuracy: 0.8655
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3453 - accuracy: 0.8733
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3303 - accuracy: 0.8778


In [15]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True) 

train_batches = data.shuffle(100).batch(10)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', 
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='Adam', loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_batches, epochs=10)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/1027 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/horses_or_humans/3.0.0.incompleteD734UZ/horses_or_humans-train.tfrecord*...:  …

Generating test examples...:   0%|          | 0/256 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/horses_or_humans/3.0.0.incompleteD734UZ/horses_or_humans-test.tfrecord*...:   …

Dataset horses_or_humans downloaded and prepared to ~/tensorflow_datasets/horses_or_humans/3.0.0. Subsequent calls will reuse this data.
Epoch 1/10
103/103 [==============================] - 13s 35ms/step - loss: 2.1710 - accuracy: 0.8500
Epoch 2/10
103/103 [==============================] - 1s 12ms/step - loss: 0.0742 - accuracy: 0.9698
Epoch 3/10
103/103 [==============================] - 1s 12ms/step - loss: 0.1705 - accuracy: 0.9416
Epoch 4/10
103/103 [==============================] - 1s 12ms/step - loss: 0.1416 - accuracy: 0.9523
Epoch 5/10
103/103 [==============================] - 1s 12ms/step - loss: 0.1014 - accuracy: 0.9708
Epoch 6/10
103/103 [==============================] - 1s 12ms/step - loss: 0.0321 - accuracy: 0.9893
Epoch 7/10
103/103 [==============================] - 1s 12ms/step - loss: 0.0155 - accuracy: 0.9942
Epoch 8/10
103/103 [==============================] - 1s 12ms/step - loss: 0.0730 - accuracy: 0.9805
Epoch 9/10
103/103 [==============================] - 

In [16]:
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)

In [17]:
validation_batches = val_data.batch(32)

In [18]:
model.fit(train_batches, epochs=10,
          validation_data=validation_batches)

Epoch 1/10
103/103 [==============================] - 2s 19ms/step - loss: 0.6644 - accuracy: 0.5784 - val_loss: 1.1155 - val_accuracy: 0.6133
Epoch 2/10
103/103 [==============================] - 1s 13ms/step - loss: 0.7236 - accuracy: 0.5355 - val_loss: 0.6937 - val_accuracy: 0.5000
Epoch 3/10
103/103 [==============================] - 1s 13ms/step - loss: 0.6824 - accuracy: 0.5365 - val_loss: 0.6940 - val_accuracy: 0.5000
Epoch 4/10
103/103 [==============================] - 1s 13ms/step - loss: 0.6932 - accuracy: 0.5131 - val_loss: 0.6932 - val_accuracy: 0.5000
Epoch 5/10
103/103 [==============================] - 1s 13ms/step - loss: 0.6932 - accuracy: 0.5131 - val_loss: 0.6933 - val_accuracy: 0.5000
Epoch 6/10
103/103 [==============================] - 1s 13ms/step - loss: 0.6931 - accuracy: 0.5131 - val_loss: 0.6933 - val_accuracy: 0.5000
Epoch 7/10
103/103 [==============================] - 1s 13ms/step - loss: 0.6933 - accuracy: 0.5131 - val_loss: 0.6933 - val_accuracy: 0.5000

### 특정 버전의 데이터셋 로드하기

In [19]:
data, info = tfds.load("horses_or_humans:3.0.0", with_info=True)

## 데이터 증식을 위해 매핑 함수 사용하기

In [20]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
train_batches = data.shuffle(100).batch(10)

In [21]:
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    return image, label

In [22]:
train = data.map(augmentimages)

In [23]:
train_batches = train.shuffle(100).batch(32)

### 텐서플로 애드온 사용하기

In [24]:
!pip install tensorflow-addons

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.1 MB 7.5 MB/s 


In [25]:
import tensorflow_addons as tfa

def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

## 사용자 정의 분할 사용하기

다운로드 파일을 찾을 수 없다는 에러(404)가 나는 경우 다운로드 경로를 직접 지정하여 사용할 수 있습니다. 예를 들어 다음처럼 cats_vs_dogs 모듈의 `_URL` 변수에 다운로드 경로를 지정합니다. cats_vs_dogs 데이터셋의 최신 다운로드 경로는 https://www.microsoft.com/en-us/download/details.aspx?id=54765 를 참고하세요.

In [26]:
tfds.image_classification.cats_vs_dogs._URL = \
    "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"

In [27]:
data = tfds.load('cats_vs_dogs', split='train', as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/1 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/23262 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/cats_vs_dogs/4.0.0.incompleteHPCCRL/cats_vs_dogs-train.tfrecord*...:   0%|    …

Dataset cats_vs_dogs downloaded and prepared to ~/tensorflow_datasets/cats_vs_dogs/4.0.0. Subsequent calls will reuse this data.


In [28]:
data = tfds.load('cats_vs_dogs', split='train[:10000]', as_supervised=True)

In [29]:
data = tfds.load('cats_vs_dogs', split='train[:20%]', as_supervised=True)

In [30]:
data = tfds.load('cats_vs_dogs', split='train[-1000:]+train[:1000]', 
                 as_supervised=True)

In [31]:
train_data = tfds.load('cats_vs_dogs', split='train[:80%]', 
                       as_supervised=True)
validation_data = tfds.load('cats_vs_dogs', split='train[80%:90%]', 
                            as_supervised=True)
test_data = tfds.load('cats_vs_dogs', split='train[-10%:]',
                       as_supervised=True)

In [32]:
train_length = [i for i,_ in enumerate(train_data)][-1] + 1
print(train_length)

18610


In [33]:
tf.data.experimental.cardinality(train_data).numpy()

18610

In [34]:
train_data, info = tfds.load('fashion_mnist', with_info=True)
print(info.splits['train'].num_examples, info.splits['test'].num_examples)

60000 10000


## TFRecord 이해하기

In [35]:
data, info = tfds.load("mnist", with_info=True)
print(info)

Dl Completed...:   0%|          | 0/4 [00:00<?, ? file/s]

Dataset mnist downloaded and prepared to ~/tensorflow_datasets/mnist/3.0.1. Subsequent calls will reuse this data.
tfds.core.DatasetInfo(
    name='mnist',
    full_name='mnist/3.0.1',
    description="""
    The MNIST database of handwritten digits.
    """,
    homepage='http://yann.lecun.com/exdb/mnist/',
    data_path='~/tensorflow_datasets/mnist/3.0.1',
    file_format=tfrecord,
    download_size=11.06 MiB,
    dataset_size=21.00 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs 

In [36]:
import os 
import sys

if 'google.colab' in sys.modules:
    filename = '/content/~/tensorflow_datasets/mnist/3.0.1/mnist-test.tfrecord-00000-of-00001'
else:
    filename = os.path.join(os.path.expanduser('~') + 
                            '/tensorflow_datasets/mnist/3.0.1/mnist-test.tfrecord-00000-of-00001')
raw_dataset = tf.data.TFRecordDataset(filename)

for raw_record in raw_dataset.take(1):
    print(repr(raw_record))

<tf.Tensor: shape=(), dtype=string, numpy=b"\n\x85\x03\n\xf2\x02\n\x05image\x12\xe8\x02\n\xe5\x02\n\xe2\x02\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc

In [37]:
# 특성 디스크립션을 만듭니다.
feature_description = {
    'image': tf.io.FixedLenFeature([], dtype=tf.string),
    'label': tf.io.FixedLenFeature([], dtype=tf.int64),
}

def _parse_function(example_proto):
    # 위에서 만든 딕셔너리로 입력을 파싱합니다.
    return tf.io.parse_single_example(example_proto, feature_description)

parsed_dataset = raw_dataset.map(_parse_function)
for parsed_record in parsed_dataset.take(1):
    print((parsed_record))

{'image': <tf.Tensor: shape=(), dtype=string, numpy=b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc9\x8b55\xe7M\xef\xb0\x04\xc0\xfd&\x89\x01<\xbe\xf9\x0

## 텐서플로에서 데이터 관리를 위한 ETL 프로세스

In [38]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_addons as tfa

# 모델 정의 시작 #
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', 
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='Adam', loss='binary_crossentropy', 
              metrics=['accuracy'])
# 모델 정의 끝 #

# 추출 단계 시작 #
data = tfds.load('horses_or_humans', split='train', 
                 as_supervised=True)
val_data = tfds.load('horses_or_humans', split='test', 
                     as_supervised=True)
# 추출 단계 끝 #

# 변환 단계 시작 #
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

train = data.map(augmentimages)
train_batches = train.shuffle(100).batch(32)
validation_batches = val_data.batch(32)
# 변환 단계 끝 #

# 로드 단계 시작 #
history = model.fit(train_batches, epochs=10, 
                    validation_data=validation_batches)
# 로드 단계 끝 #

Epoch 1/10
33/33 [==============================] - 11s 278ms/step - loss: 0.4002 - accuracy: 0.8023 - val_loss: 243.4170 - val_accuracy: 0.4844
Epoch 2/10
33/33 [==============================] - 7s 208ms/step - loss: 0.1826 - accuracy: 0.9289 - val_loss: 399.1703 - val_accuracy: 0.4609
Epoch 3/10
33/33 [==============================] - 7s 206ms/step - loss: 0.0775 - accuracy: 0.9727 - val_loss: 318.9698 - val_accuracy: 0.5820
Epoch 4/10
33/33 [==============================] - 8s 213ms/step - loss: 0.0858 - accuracy: 0.9630 - val_loss: 258.2326 - val_accuracy: 0.6016
Epoch 5/10
33/33 [==============================] - 7s 205ms/step - loss: 0.0378 - accuracy: 0.9893 - val_loss: 332.6216 - val_accuracy: 0.5625
Epoch 6/10
33/33 [==============================] - 7s 205ms/step - loss: 0.0328 - accuracy: 0.9922 - val_loss: 499.0999 - val_accuracy: 0.5195
Epoch 7/10
33/33 [==============================] - 7s 208ms/step - loss: 0.0932 - accuracy: 0.9669 - val_loss: 1889.1381 - val_accurac

### 훈련 속도 향상을 위한 ETL 병렬화

In [39]:
train_data = tfds.load('cats_vs_dogs', split='train', with_info=True)

In [41]:
import sys

if 'google.colab' in sys.modules:
    file_pattern = '/content/~/tensorflow_datasets/cats_vs_dogs/4.0.0/cats_vs_dogs-train.tfrecord*'
else:
    file_pattern = os.path.join(
        os.path.expanduser('~') + 
        '/tensorflow_datasets/cats_vs_dogs/4.0.0/cats_vs_dogs-train.tfrecord*'
    )
files = tf.data.Dataset.list_files(file_pattern)

In [42]:
train_dataset = files.interleave(
    tf.data.TFRecordDataset, 
    cycle_length=4,
    num_parallel_calls=tf.data.experimental.AUTOTUNE
)

In [43]:
def read_tfrecord(serialized_example):
    feature_description={
        "image": tf.io.FixedLenFeature((), tf.string, ""),
        "label": tf.io.FixedLenFeature((), tf.int64, -1),
    }
    example = tf.io.parse_single_example(
        serialized_example, feature_description
    )
    image = tf.io.decode_jpeg(example['image'], channels=3)
    image = tf.cast(image, tf.float32)
    image = image / 255
    image = tf.image.resize(image, (300,300))
    return image, example['label']

In [44]:
import multiprocessing

cores = multiprocessing.cpu_count()
print(cores)
train_dataset = train_dataset.map(read_tfrecord, num_parallel_calls=cores)
# 코랩의 경우 데이터셋을 캐싱하면 메모리 부족으로 런타임이 다운될 수 있으므로 주석처리힙니다.
# train_dataset = train_dataset.cache()

2


In [45]:
train_dataset = train_dataset.shuffle(1024).batch(32)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)

In [46]:
model.fit(train_dataset, epochs=10, verbose=1)

Epoch 1/10
727/727 [==============================] - 56s 75ms/step - loss: 0.6751 - accuracy: 0.5864
Epoch 2/10
727/727 [==============================] - 57s 76ms/step - loss: 0.5795 - accuracy: 0.6954
Epoch 3/10
727/727 [==============================] - 56s 74ms/step - loss: 0.4809 - accuracy: 0.7685
Epoch 4/10
727/727 [==============================] - 56s 75ms/step - loss: 0.3860 - accuracy: 0.8269
Epoch 5/10
727/727 [==============================] - 56s 75ms/step - loss: 0.3045 - accuracy: 0.8664
Epoch 6/10
727/727 [==============================] - 56s 75ms/step - loss: 0.2455 - accuracy: 0.8964
Epoch 7/10
727/727 [==============================] - 56s 75ms/step - loss: 0.1769 - accuracy: 0.9270
Epoch 8/10
727/727 [==============================] - 56s 75ms/step - loss: 0.1287 - accuracy: 0.9496
Epoch 9/10
727/727 [==============================] - 56s 75ms/step - loss: 0.0996 - accuracy: 0.9620
Epoch 10/10
727/727 [==============================] - 56s 75ms/step - loss: 0.060