# 4장. 텐서플로 데이터셋으로 공개 데이터 사용하기

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://nbviewer.jupyter.org/github/rickiepark/aiml4coders/blob/main/ch04/04-tfds.ipynb"><img src="https://jupyter.org/assets/share.png" width="61" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/aiml4coders/blob/main/ch04/04-tfds.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

## TFDS 시작하기

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds

mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
    print(item)

train
test


2022-03-01 04:33:49.676380: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>


In [3]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


2022-03-01 04:33:49.868456: W tensorflow/core/kernels/data/cache_dataset_ops.cc:768] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [4]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


2022-03-01 04:33:49.932028: W tensorflow/core/kernels/data/cache_dataset_ops.cc:768] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


In [5]:
mnist_test, info = tfds.load(name="fashion_mnist", with_info="true")
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_path='/home/haesun/tensorflow_datasets/fashion_mnist/3.0.1',
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author    = {Han Xiao a

## 케라스 모델에서 TFDS 사용하기

In [6]:
mnist = tf.keras.datasets.fashion_mnist

(training_images, training_labels), (test_images, test_labels) = \
    mnist.load_data()

In [7]:
(training_images, training_labels), (test_images, test_labels) = \
    tfds.as_numpy(tfds.load('fashion_mnist',
                            split = ['train', 'test'], 
                            batch_size=-1, 
                            as_supervised=True))

In [8]:
(training_images, training_labels), (test_images, test_labels) = \
    tfds.load('fashion_mnist', 
              split = ['train', 'test'],
              batch_size=-1, 
              as_supervised=True)

training_images = tf.cast(training_images, tf.float32) / 255.0
test_images = tf.cast(test_images, tf.float32) / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28,1)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.5259 - accuracy: 0.8130
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3997 - accuracy: 0.8540
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3686 - accuracy: 0.8656
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3445 - accuracy: 0.8731
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3286 - accuracy: 0.8777


In [9]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True) 

train_batches = data.shuffle(100).batch(10)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3,3), activation='relu', 
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='Adam', loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_batches, epochs=10)

Epoch 1/10
103/103 [==============================] - 31s 292ms/step - loss: 2.9181 - accuracy: 0.8053
Epoch 2/10
103/103 [==============================] - 29s 279ms/step - loss: 0.1262 - accuracy: 0.9562
Epoch 3/10
103/103 [==============================] - 30s 295ms/step - loss: 0.1090 - accuracy: 0.9688
Epoch 4/10
103/103 [==============================] - 29s 279ms/step - loss: 0.1605 - accuracy: 0.9572
Epoch 5/10
103/103 [==============================] - 29s 280ms/step - loss: 0.0869 - accuracy: 0.9747
Epoch 6/10
103/103 [==============================] - 29s 279ms/step - loss: 0.0496 - accuracy: 0.9834
Epoch 7/10
103/103 [==============================] - 29s 282ms/step - loss: 0.0116 - accuracy: 0.9951
Epoch 8/10
103/103 [==============================] - 29s 282ms/step - loss: 6.7040e-04 - accuracy: 1.0000
Epoch 9/10
103/103 [==============================] - 29s 281ms/step - loss: 1.7499e-04 - accuracy: 1.0000
Epoch 10/10
103/103 [==============================] - 29s 281ms/

In [10]:
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)

In [11]:
validation_batches = val_data.batch(32)

In [12]:
model.fit(train_batches, epochs=10,
          validation_data=validation_batches)

Epoch 1/10
103/103 [==============================] - 31s 300ms/step - loss: 5.0541e-05 - accuracy: 1.0000 - val_loss: 3.1031 - val_accuracy: 0.8633
Epoch 2/10
103/103 [==============================] - 30s 295ms/step - loss: 4.0494e-05 - accuracy: 1.0000 - val_loss: 3.1764 - val_accuracy: 0.8633
Epoch 3/10
103/103 [==============================] - 30s 295ms/step - loss: 3.3339e-05 - accuracy: 1.0000 - val_loss: 3.2435 - val_accuracy: 0.8594
Epoch 4/10
103/103 [==============================] - 30s 296ms/step - loss: 2.8903e-05 - accuracy: 1.0000 - val_loss: 3.3048 - val_accuracy: 0.8594
Epoch 5/10
103/103 [==============================] - 30s 294ms/step - loss: 2.4731e-05 - accuracy: 1.0000 - val_loss: 3.3506 - val_accuracy: 0.8594
Epoch 6/10
103/103 [==============================] - 31s 299ms/step - loss: 2.1547e-05 - accuracy: 1.0000 - val_loss: 3.4111 - val_accuracy: 0.8555
Epoch 7/10
103/103 [==============================] - 31s 299ms/step - loss: 1.8975e-05 - accuracy: 1.0000

### 특정 버전의 데이터셋 로드하기

In [13]:
data, info = tfds.load("horses_or_humans:3.0.0", with_info=True)

## 데이터 증식을 위해 매핑 함수 사용하기

In [14]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
train_batches = data.shuffle(100).batch(10)

In [15]:
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    return image, label

In [16]:
train = data.map(augmentimages)

In [17]:
train_batches = train.shuffle(100).batch(32)

### 텐서플로 애드온 사용하기

In [18]:
!pip install tensorflow-addons

In [19]:
import tensorflow_addons as tfa

def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

## 사용자 정의 분할 사용하기

In [20]:
data = tfds.load('cats_vs_dogs', split='train', as_supervised=True)

In [21]:
data = tfds.load('cats_vs_dogs', split='train[:10000]', as_supervised=True)

In [22]:
data = tfds.load('cats_vs_dogs', split='train[:20%]', as_supervised=True)

In [23]:
data = tfds.load('cats_vs_dogs', split='train[-1000:]+train[:1000]', 
                 as_supervised=True)

In [24]:
train_data = tfds.load('cats_vs_dogs', split='train[:80%]', 
                       as_supervised=True)
validation_data = tfds.load('cats_vs_dogs', split='train[80%:90%]', 
                            as_supervised=True)
test_data = tfds.load('cats_vs_dogs', split='train[-10%:]',
                       as_supervised=True)

In [25]:
train_length = [i for i,_ in enumerate(train_data)][-1] + 1
print(train_length)

Corrupt JPEG data: 99 extraneous bytes before marker 0xd9
Corrupt JPEG data: 396 extraneous bytes before marker 0xd9
Corrupt JPEG data: 65 extraneous bytes before marker 0xd9
Corrupt JPEG data: 2226 extraneous bytes before marker 0xd9
Corrupt JPEG data: 128 extraneous bytes before marker 0xd9
Corrupt JPEG data: 239 extraneous bytes before marker 0xd9


18610


Corrupt JPEG data: 1153 extraneous bytes before marker 0xd9
Corrupt JPEG data: 228 extraneous bytes before marker 0xd9


In [26]:
tf.data.experimental.cardinality(train_data).numpy()

18610

In [27]:
train_data, info = tfds.load('fashion_mnist', with_info=True)
print(info.splits['train'].num_examples, info.splits['test'].num_examples)

60000 10000


## TFRecord 이해하기

In [28]:
data, info = tfds.load("mnist", with_info=True)
print(info)

tfds.core.DatasetInfo(
    name='mnist',
    full_name='mnist/3.0.1',
    description="""
    The MNIST database of handwritten digits.
    """,
    homepage='http://yann.lecun.com/exdb/mnist/',
    data_path='/home/haesun/tensorflow_datasets/mnist/3.0.1',
    download_size=11.06 MiB,
    dataset_size=21.00 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann.lecun.com/exdb/mnist},
      volume={2},
      year={2010}
    }""",
)


In [29]:
import os 

filename = os.path.join(os.path.expanduser('~') + 
                        '/tensorflow_datasets/mnist/3.0.1/mnist-test.tfrecord-00000-of-00001')
raw_dataset = tf.data.TFRecordDataset(filename)

for raw_record in raw_dataset.take(1):
    print(repr(raw_record))

<tf.Tensor: shape=(), dtype=string, numpy=b"\n\x85\x03\n\xf2\x02\n\x05image\x12\xe8\x02\n\xe5\x02\n\xe2\x02\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc

In [30]:
# 특성 디스크립션을 만듭니다.
feature_description = {
    'image': tf.io.FixedLenFeature([], dtype=tf.string),
    'label': tf.io.FixedLenFeature([], dtype=tf.int64),
}

def _parse_function(example_proto):
    # 위에서 만든 딕셔너리로 입력을 파싱합니다.
    return tf.io.parse_single_example(example_proto, feature_description)

parsed_dataset = raw_dataset.map(_parse_function)
for parsed_record in parsed_dataset.take(1):
    print((parsed_record))

{'image': <tf.Tensor: shape=(), dtype=string, numpy=b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc9\x8b55\xe7M\xef\xb0\x04\xc0\xfd&\x89\x01<\xbe\xf9\x0

## 텐서플로에서 데이터 관리를 위한 ETL 프로세스

In [31]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_addons as tfa

# 모델 정의 시작 #
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3,3), activation='relu', 
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D(2, 2),
    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='Adam', loss='binary_crossentropy', 
              metrics=['accuracy'])
# 모델 정의 끝 #

# 추출 단계 시작 #
data = tfds.load('horses_or_humans', split='train', 
                 as_supervised=True)
val_data = tfds.load('horses_or_humans', split='test', 
                     as_supervised=True)
# 추출 단계 끝 #

# 변환 단계 시작 #
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

train = data.map(augmentimages)
train_batches = train.shuffle(100).batch(32)
validation_batches = val_data.batch(32)
# 변환 단계 끝 #

# 로드 단계 시작 #
history = model.fit(train_batches, epochs=10, 
                    validation_data=validation_batches)
# 로드 단계 끝 #

Epoch 1/10
33/33 [==============================] - 36s 1s/step - loss: 0.4573 - accuracy: 0.7741 - val_loss: 416.3230 - val_accuracy: 0.4375
Epoch 2/10
33/33 [==============================] - 35s 1s/step - loss: 0.1263 - accuracy: 0.9533 - val_loss: 575.7719 - val_accuracy: 0.4141
Epoch 3/10
33/33 [==============================] - 35s 1s/step - loss: 0.1213 - accuracy: 0.9630 - val_loss: 636.6270 - val_accuracy: 0.4648
Epoch 4/10
33/33 [==============================] - 35s 1s/step - loss: 0.0494 - accuracy: 0.9825 - val_loss: 760.9930 - val_accuracy: 0.3750
Epoch 5/10
33/33 [==============================] - 35s 1s/step - loss: 0.1411 - accuracy: 0.9474 - val_loss: 297.4895 - val_accuracy: 0.3984
Epoch 6/10
33/33 [==============================] - 35s 1s/step - loss: 0.0692 - accuracy: 0.9796 - val_loss: 482.3256 - val_accuracy: 0.4375
Epoch 7/10
33/33 [==============================] - 35s 1s/step - loss: 0.0179 - accuracy: 0.9932 - val_loss: 418.0457 - val_accuracy: 0.4805
Epoch 

### 훈련 속도 향상을 위한 ETL 병렬화

In [32]:
train_data = tfds.load('cats_vs_dogs', split='train', with_info=True)

In [33]:
file_pattern = os.path.join(
    os.path.expanduser('~') + 
    '/tensorflow_datasets/cats_vs_dogs/4.0.0/cats_vs_dogs-train.tfrecord*'
)
files = tf.data.Dataset.list_files(file_pattern)

In [34]:
train_dataset = files.interleave(
    tf.data.TFRecordDataset, 
    cycle_length=4,
    num_parallel_calls=tf.data.experimental.AUTOTUNE
)

In [35]:
def read_tfrecord(serialized_example):
    feature_description={
        "image": tf.io.FixedLenFeature((), tf.string, ""),
        "label": tf.io.FixedLenFeature((), tf.int64, -1),
    }
    example = tf.io.parse_single_example(
        serialized_example, feature_description
    )
    image = tf.io.decode_jpeg(example['image'], channels=3)
    image = tf.cast(image, tf.float32)
    image = image / 255
    image = tf.image.resize(image, (300,300))
    return image, example['label']

In [36]:
import multiprocessing

cores = multiprocessing.cpu_count()
print(cores)
train_dataset = train_dataset.map(read_tfrecord, num_parallel_calls=cores)
train_dataset = train_dataset.cache()

8


In [37]:
train_dataset = train_dataset.shuffle(1024).batch(32)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)

In [38]:
model.fit(train_dataset, epochs=10, verbose=1)

Epoch 1/10
     80/Unknown - 66s 812ms/step - loss: 0.7724 - accuracy: 0.5066

Corrupt JPEG data: 99 extraneous bytes before marker 0xd9


    103/Unknown - 84s 810ms/step - loss: 0.7546 - accuracy: 0.5049

Corrupt JPEG data: 396 extraneous bytes before marker 0xd9


    289/Unknown - 236s 812ms/step - loss: 0.7149 - accuracy: 0.5138

Corrupt JPEG data: 2226 extraneous bytes before marker 0xd9


    297/Unknown - 242s 812ms/step - loss: 0.7144 - accuracy: 0.5130

Corrupt JPEG data: 128 extraneous bytes before marker 0xd9


    460/Unknown - 374s 811ms/step - loss: 0.7040 - accuracy: 0.5258

    488/Unknown - 397s 811ms/step - loss: 0.7029 - accuracy: 0.5260

Corrupt JPEG data: 162 extraneous bytes before marker 0xd9


    513/Unknown - 417s 811ms/step - loss: 0.7015 - accuracy: 0.5294

Corrupt JPEG data: 252 extraneous bytes before marker 0xd9


    515/Unknown - 418s 811ms/step - loss: 0.7015 - accuracy: 0.5295

Corrupt JPEG data: 65 extraneous bytes before marker 0xd9


    521/Unknown - 423s 811ms/step - loss: 0.7013 - accuracy: 0.5296

Corrupt JPEG data: 1403 extraneous bytes before marker 0xd9


    602/Unknown - 489s 811ms/step - loss: 0.6984 - accuracy: 0.5349

Corrupt JPEG data: 214 extraneous bytes before marker 0xd9


    668/Unknown - 543s 811ms/step - loss: 0.6948 - accuracy: 0.5418

Corrupt JPEG data: 239 extraneous bytes before marker 0xd9


    686/Unknown - 557s 811ms/step - loss: 0.6943 - accuracy: 0.5426

Corrupt JPEG data: 1153 extraneous bytes before marker 0xd9


    691/Unknown - 562s 812ms/step - loss: 0.6941 - accuracy: 0.5430

Corrupt JPEG data: 228 extraneous bytes before marker 0xd9


727/727 [==============================] - 593s 814ms/step - loss: 0.6913 - accuracy: 0.5478
Epoch 2/10
727/727 [==============================] - 609s 837ms/step - loss: 0.5845 - accuracy: 0.6909
Epoch 3/10
727/727 [==============================] - 613s 844ms/step - loss: 0.4792 - accuracy: 0.7664
Epoch 4/10
727/727 [==============================] - 621s 855ms/step - loss: 0.4029 - accuracy: 0.8169
Epoch 5/10
727/727 [==============================] - 618s 851ms/step - loss: 0.3381 - accuracy: 0.8492
Epoch 6/10
727/727 [==============================] - 618s 850ms/step - loss: 0.2671 - accuracy: 0.8881
Epoch 7/10
727/727 [==============================] - 625s 859ms/step - loss: 0.1962 - accuracy: 0.9183
Epoch 8/10
727/727 [==============================] - 618s 850ms/step - loss: 0.1382 - accuracy: 0.9451
Epoch 9/10
727/727 [==============================] - 618s 850ms/step - loss: 0.0850 - accuracy: 0.9661
Epoch 10/10
727/727 [==============================] - 621s 854ms/step - lo