# 4장. 텐서플로 데이터셋으로 공개 데이터 사용하기

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://nbviewer.jupyter.org/github/rickiepark/aiml4coders/blob/main/ch04/04-tfds.ipynb"><img src="https://jupyter.org/assets/share.png" width="61" />주피터 노트북 뷰어로 보기</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/aiml4coders/blob/main/ch04/04-tfds.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩(Colab)에서 실행하기</a>
  </td>
</table>

## TFDS 시작하기

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds

mnist_data = tfds.load("fashion_mnist")
for item in mnist_data:
    print(item)

test
train


In [2]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>


In [3]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


In [4]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


In [5]:
mnist_test, info = tfds.load(name="fashion_mnist", with_info="true")
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    version=3.0.1,
    description='Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.',
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    total_num_examples=70000,
    splits={
        'test': 10000,
        'train': 60000,
    },
    supervised_keys=('image', 'label'),
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author    = {Han Xiao and
                   Kashif Rasul and
                   Roland Vollgraf},
      title     = {Fashion-MNIST: a Novel Image Dataset for Benchmarking Machine Learning
                   Algorithms},
      journal   = {CoRR},
      volume

## 케라스 모델에서 TFDS 사용하기

In [6]:
mnist = tf.keras.datasets.fashion_mnist

(training_images, training_labels), (test_images, test_labels) = \
    mnist.load_data()

In [7]:
(training_images, training_labels), (test_images, test_labels) = \
    tfds.as_numpy(tfds.load('fashion_mnist',
                            split = ['train', 'test'], 
                            batch_size=-1, 
                            as_supervised=True))

Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


In [8]:
(training_images, training_labels), (test_images, test_labels) = \
    tfds.load('fashion_mnist', 
              split = ['train', 'test'],
              batch_size=-1, 
              as_supervised=True)

training_images = tf.cast(training_images, tf.float32) / 255.0
test_images = tf.cast(test_images, tf.float32) / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28,1)),
    tf.keras.layers.Dense(128, activation=tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 2ms/step - loss: 0.5286 - accuracy: 0.8135
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3999 - accuracy: 0.8550
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3682 - accuracy: 0.8663
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3464 - accuracy: 0.8730
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3302 - accuracy: 0.8784


In [9]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True) 

train_batches = data.shuffle(100).batch(10)

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', 
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='Adam', loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(train_batches, epochs=10)

Epoch 1/10
103/103 [==============================] - 15s 50ms/step - loss: 2.0467 - accuracy: 0.8452
Epoch 2/10
103/103 [==============================] - 5s 44ms/step - loss: 0.0874 - accuracy: 0.9708
Epoch 3/10
103/103 [==============================] - 5s 45ms/step - loss: 0.1068 - accuracy: 0.9766
Epoch 4/10
103/103 [==============================] - 5s 45ms/step - loss: 0.0922 - accuracy: 0.9688
Epoch 5/10
103/103 [==============================] - 5s 47ms/step - loss: 0.0583 - accuracy: 0.9776
Epoch 6/10
103/103 [==============================] - 5s 44ms/step - loss: 0.2314 - accuracy: 0.9464
Epoch 7/10
103/103 [==============================] - 5s 46ms/step - loss: 0.0079 - accuracy: 0.9971
Epoch 8/10
103/103 [==============================] - 5s 45ms/step - loss: 0.0253 - accuracy: 0.9903
Epoch 9/10
103/103 [==============================] - 5s 44ms/step - loss: 0.0441 - accuracy: 0.9844
Epoch 10/10
103/103 [==============================] - 5s 44ms/step - loss: 0.0423 - accur

In [10]:
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)

In [11]:
validation_batches = val_data.batch(32)

In [12]:
model.fit(train_batches, epochs=10,
          validation_data=validation_batches)

Epoch 1/10
103/103 [==============================] - 6s 55ms/step - loss: 0.0018 - accuracy: 0.9990 - val_loss: 4.3995 - val_accuracy: 0.8359
Epoch 2/10
103/103 [==============================] - 6s 53ms/step - loss: 1.1711e-04 - accuracy: 1.0000 - val_loss: 4.5387 - val_accuracy: 0.8359
Epoch 3/10
103/103 [==============================] - 6s 50ms/step - loss: 7.7254e-05 - accuracy: 1.0000 - val_loss: 4.5758 - val_accuracy: 0.8359
Epoch 4/10
103/103 [==============================] - 6s 51ms/step - loss: 5.5316e-05 - accuracy: 1.0000 - val_loss: 4.6251 - val_accuracy: 0.8398
Epoch 5/10
103/103 [==============================] - 6s 52ms/step - loss: 4.3427e-05 - accuracy: 1.0000 - val_loss: 4.6837 - val_accuracy: 0.8398
Epoch 6/10
103/103 [==============================] - 6s 52ms/step - loss: 3.5382e-05 - accuracy: 1.0000 - val_loss: 4.7269 - val_accuracy: 0.8359
Epoch 7/10
103/103 [==============================] - 6s 52ms/step - loss: 3.0126e-05 - accuracy: 1.0000 - val_loss: 4.760

### 특정 버전의 데이터셋 로드하기

In [13]:
data, info = tfds.load("horses_or_humans:3.0.0", with_info=True)

## 데이터 증식을 위해 매핑 함수 사용하기

In [14]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
train_batches = data.shuffle(100).batch(10)

In [15]:
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    return image, label

In [16]:
train = data.map(augmentimages)

In [17]:
train_batches = train.shuffle(100).batch(32)

### 텐서플로 애드온 사용하기

In [18]:
!pip install tensorflow-addons

In [19]:
import tensorflow_addons as tfa

def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

## 사용자 정의 분할 사용하기

다운로드 파일을 찾을 수 없다는 에러(404)가 나는 경우 다운로드 경로를 직접 지정하여 사용할 수 있습니다. 예를 들어 다음처럼 cats_vs_dogs 모듈의 `_URL` 변수에 다운로드 경로를 지정합니다. cats_vs_dogs 데이터셋의 최신 다운로드 경로는 https://www.microsoft.com/en-us/download/details.aspx?id=54765 를 참고하세요.

In [20]:
tfds.image_classification.cats_vs_dogs._URL = \
    "https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"

In [21]:
data = tfds.load('cats_vs_dogs', split='train', as_supervised=True)

In [22]:
data = tfds.load('cats_vs_dogs', split='train[:10000]', as_supervised=True)

In [23]:
data = tfds.load('cats_vs_dogs', split='train[:20%]', as_supervised=True)

In [24]:
data = tfds.load('cats_vs_dogs', split='train[-1000:]+train[:1000]', 
                 as_supervised=True)

In [25]:
train_data = tfds.load('cats_vs_dogs', split='train[:80%]', 
                       as_supervised=True)
validation_data = tfds.load('cats_vs_dogs', split='train[80%:90%]', 
                            as_supervised=True)
test_data = tfds.load('cats_vs_dogs', split='train[-10%:]',
                       as_supervised=True)

In [26]:
train_length = [i for i,_ in enumerate(train_data)][-1] + 1
print(train_length)

18610


In [27]:
tf.data.experimental.cardinality(train_data).numpy()

18610

In [28]:
train_data, info = tfds.load('fashion_mnist', with_info=True)
print(info.splits['train'].num_examples, info.splits['test'].num_examples)

60000 10000


## TFRecord 이해하기

In [29]:
data, info = tfds.load("mnist", with_info=True)
print(info)

tfds.core.DatasetInfo(
    name='mnist',
    version=3.0.1,
    description='The MNIST database of handwritten digits.',
    homepage='http://yann.lecun.com/exdb/mnist/',
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    total_num_examples=70000,
    splits={
        'test': 10000,
        'train': 60000,
    },
    supervised_keys=('image', 'label'),
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann.lecun.com/exdb/mnist},
      volume={2},
      year={2010}
    }""",
    redistribution_info=,
)



In [30]:
import os 

filename = os.path.join(os.path.expanduser('~') + 
                        '/tensorflow_datasets/mnist/3.0.1/mnist-test.tfrecord-00000-of-00001')
raw_dataset = tf.data.TFRecordDataset(filename)

for raw_record in raw_dataset.take(1):
    print(repr(raw_record))

<tf.Tensor: shape=(), dtype=string, numpy=b"\n\x85\x03\n\xf2\x02\n\x05image\x12\xe8\x02\n\xe5\x02\n\xe2\x02\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc

In [31]:
# 특성 디스크립션을 만듭니다.
feature_description = {
    'image': tf.io.FixedLenFeature([], dtype=tf.string),
    'label': tf.io.FixedLenFeature([], dtype=tf.int64),
}

def _parse_function(example_proto):
    # 위에서 만든 딕셔너리로 입력을 파싱합니다.
    return tf.io.parse_single_example(example_proto, feature_description)

parsed_dataset = raw_dataset.map(_parse_function)
for parsed_record in parsed_dataset.take(1):
    print((parsed_record))

{'image': <tf.Tensor: shape=(), dtype=string, numpy=b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x1c\x00\x00\x00\x1c\x08\x00\x00\x00\x00Wf\x80H\x00\x00\x01)IDAT(\x91\xc5\xd2\xbdK\xc3P\x14\x05\xf0S(v\x13)\x04,.\x82\xc5Aq\xac\xedb\x1d\xdc\n.\x12\x87n\x0e\x82\x93\x7f@Q\xb2\x08\xba\tbQ0.\xe2\xe2\xd4\xb1\xa2h\x9c\x82\xba\x8a(\nq\xf0\x83Fh\x95\n6\x88\xe7R\x87\x88\xf9\xa8Y\xf5\x0e\x8f\xc7\xfd\xdd\x0b\x87\xc7\x03\xfe\xbeb\x9d\xadT\x927Q\xe3\xe9\x07:\xab\xbf\xf4\xf3\xcf\xf6\x8a\xd9\x14\xd29\xea\xb0\x1eKH\xde\xab\xea%\xaba\x1b=\xa4P/\xf5\x02\xd7\\\x07\x00\xc4=,L\xc0,>\x01@2\xf6\x12\xde\x9c\xde[t/\xb3\x0e\x87\xa2\xe2\xc2\xe0A<\xca\xb26\xd5(\x1b\xa9\xd3\xe8\x0e\xf5\x86\x17\xceE\xdarV\xae\xb7_\xf3AR\r!I\xf7(\x06m\xaaE\xbb\xb6\xac\r*\x9b$e<\xb8\xd7\xa2\x0e\x00\xd0l\x92\xb2\xd5\x15\xcc\xae'\x00\xf4m\x08O'+\xc2y\x9f\x8d\xc9\x15\x80\xfe\x99[q\x962@CN|i\xf7\xa9!=\xd7 \xab\x19\x00\xc8\xd6\xb8\xeb\xa1\xf0\xd8l\xca\xfb]\xee\xfb]*\x9fV\xe1\x07\xb7\xc9\x8b55\xe7M\xef\xb0\x04\xc0\xfd&\x89\x01<\xbe\xf9\x0

## 텐서플로에서 데이터 관리를 위한 ETL 프로세스

In [32]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_addons as tfa

# 모델 정의 시작 #
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation='relu', 
                           input_shape=(300, 300, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='Adam', loss='binary_crossentropy', 
              metrics=['accuracy'])
# 모델 정의 끝 #

# 추출 단계 시작 #
data = tfds.load('horses_or_humans', split='train', 
                 as_supervised=True)
val_data = tfds.load('horses_or_humans', split='test', 
                     as_supervised=True)
# 추출 단계 끝 #

# 변환 단계 시작 #
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label

train = data.map(augmentimages)
train_batches = train.shuffle(100).batch(32)
validation_batches = val_data.batch(32)
# 변환 단계 끝 #

# 로드 단계 시작 #
history = model.fit(train_batches, epochs=10, 
                    validation_data=validation_batches)
# 로드 단계 끝 #

Epoch 1/10
33/33 [==============================] - 27s 758ms/step - loss: 0.5011 - accuracy: 0.7556 - val_loss: 294.0117 - val_accuracy: 0.6211
Epoch 2/10
33/33 [==============================] - 13s 369ms/step - loss: 0.1332 - accuracy: 0.9406 - val_loss: 569.8804 - val_accuracy: 0.4766
Epoch 3/10
33/33 [==============================] - 13s 362ms/step - loss: 0.0461 - accuracy: 0.9786 - val_loss: 498.3898 - val_accuracy: 0.4766
Epoch 4/10
33/33 [==============================] - 13s 375ms/step - loss: 0.0233 - accuracy: 0.9912 - val_loss: 563.0200 - val_accuracy: 0.6523
Epoch 5/10
33/33 [==============================] - 13s 370ms/step - loss: 0.1343 - accuracy: 0.9562 - val_loss: 161.0210 - val_accuracy: 0.6758
Epoch 6/10
33/33 [==============================] - 13s 364ms/step - loss: 0.0867 - accuracy: 0.9640 - val_loss: 767.5318 - val_accuracy: 0.5273
Epoch 7/10
33/33 [==============================] - 15s 411ms/step - loss: 0.0089 - accuracy: 0.9971 - val_loss: 637.2518 - val_ac

### 훈련 속도 향상을 위한 ETL 병렬화

In [33]:
train_data = tfds.load('cats_vs_dogs', split='train', with_info=True)

In [34]:
file_pattern = os.path.join(
    os.path.expanduser('~') + 
    '/tensorflow_datasets/cats_vs_dogs/4.0.0/cats_vs_dogs-train.tfrecord*'
)
files = tf.data.Dataset.list_files(file_pattern)

In [35]:
train_dataset = files.interleave(
    tf.data.TFRecordDataset, 
    cycle_length=4,
    num_parallel_calls=tf.data.experimental.AUTOTUNE
)

In [36]:
def read_tfrecord(serialized_example):
    feature_description={
        "image": tf.io.FixedLenFeature((), tf.string, ""),
        "label": tf.io.FixedLenFeature((), tf.int64, -1),
    }
    example = tf.io.parse_single_example(
        serialized_example, feature_description
    )
    image = tf.io.decode_jpeg(example['image'], channels=3)
    image = tf.cast(image, tf.float32)
    image = image / 255
    image = tf.image.resize(image, (300,300))
    return image, example['label']

In [37]:
import multiprocessing

cores = multiprocessing.cpu_count()
print(cores)
train_dataset = train_dataset.map(read_tfrecord, num_parallel_calls=cores)
# train_dataset = train_dataset.cache()

2


In [38]:
train_dataset = train_dataset.shuffle(1024).batch(16)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)

In [39]:
model.fit(train_dataset, epochs=10, verbose=1)

Epoch 1/10
1454/1454 [==============================] - 69s 46ms/step - loss: 0.6212 - accuracy: 0.6484
Epoch 2/10
1454/1454 [==============================] - 68s 45ms/step - loss: 0.4835 - accuracy: 0.7677
Epoch 3/10
1454/1454 [==============================] - 68s 46ms/step - loss: 0.4105 - accuracy: 0.8115
Epoch 4/10
1454/1454 [==============================] - 67s 45ms/step - loss: 0.3409 - accuracy: 0.8485
Epoch 5/10
1454/1454 [==============================] - 68s 46ms/step - loss: 0.2801 - accuracy: 0.8798
Epoch 6/10
1454/1454 [==============================] - 69s 46ms/step - loss: 0.2080 - accuracy: 0.9147
Epoch 7/10
1454/1454 [==============================] - 68s 46ms/step - loss: 0.1461 - accuracy: 0.9402
Epoch 8/10
1454/1454 [==============================] - 69s 46ms/step - loss: 0.1042 - accuracy: 0.9601
Epoch 9/10
1454/1454 [==============================] - 69s 46ms/step - loss: 0.0789 - accuracy: 0.9713
Epoch 10/10
1454/1454 [==============================] - 68s 45m